version: '3.1'

services:
  db:
    image: mongo
    container_name: test_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      default:
        ipv4_address: 172.16.1.2
  api:
    build: api
    container_name: test_api
    restart: always
    ports:
      - 8081:8081
    links:
      - db
    networks:
      default:
        ipv4_address: 172.16.1.3
networks:
   default:
     driver: bridge
     ipam:
       config:
         - subnet: 172.16.1.0/24
